{% set version = "0.0.2" %}

package:
  name: aemcmc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aemcmc/aemcmc-{{ version }}.tar.gz
  sha256: 870f272da16378af7b04f40fdda13c0e15db4d1c72f9500029b024fb700f9104

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.18.1
    - scipy >=1.4.0
    - aesara >=2.1.1
    - aeppl >=0.0.5
    - polyagamma >=1.3.2

test:
  imports:
    - aemcmc
    - aemcmc.dists

about:
  home: https://github.com/aesara-devs/aemcmc
  license: MIT
  summary: Miscellaneous MCMC samplers written in Aesara
  license_file: LICENSE
  dev_url: https://github.com/aesara-devs/aemcmc/

extra:
  recipe-maintainers:
    - brandonwillard
    - zoj613
    - rlouf
